"""add ecg round tables

Revision ID: 79d61a1c7a82
Revises: 0a85b88c16a7
Create Date: 2026-05-08 21:12:19.325189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79d61a1c7a82'
down_revision = '0a85b88c16a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecg_round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('aggregation_type', sa.String(length=20), nullable=True),
    sa.Column('global_model_path', sa.String(length=256), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecg_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('weights_path', sa.String(length=256), nullable=True),
    sa.Column('num_samples', sa.Integer(), nullable=True),
    sa.Column('local_accuracy', sa.Float(), nullable=True),
    sa.Column('local_loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['ecg_round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecg_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=True),
    sa.Column('filename', sa.String(length=128), nullable=True),
    sa.Column('lead_used', sa.String(length=20), nullable=True),
    sa.Column('num_timesteps', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('used_in_training', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ecg_prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('ecg_upload_id', sa.Integer(), nullable=True),
    sa.Column('prediction', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rr_cv', sa.Float(), nullable=True),
    sa.Column('num_r_peaks', sa.Integer(), nullable=True),
    sa.Column('ml_raw_prediction', sa.String(length=20), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=True),
    sa.Column('clinical_reason', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['ecg_upload_id'], ['ecg_upload.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ecg_prediction')
    op.drop_table('ecg_upload')
    op.drop_table('ecg_update')
    op.drop_table('ecg_round')
    # ### end Alembic commands ###
